package com.luis.poem.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.luis.poem.bean.PoemBean;

import com.luis.poem.greendao.PoemBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poemBeanDaoConfig;

    private final PoemBeanDao poemBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poemBeanDaoConfig = daoConfigMap.get(PoemBeanDao.class).clone();
        poemBeanDaoConfig.initIdentityScope(type);

        poemBeanDao = new PoemBeanDao(poemBeanDaoConfig, this);

        registerDao(PoemBean.class, poemBeanDao);
    }
    
    public void clear() {
        poemBeanDaoConfig.clearIdentityScope();
    }

    public PoemBeanDao getPoemBeanDao() {
        return poemBeanDao;
    }

}
